version: "3"

services:
  node:
    # コンテナ名
    container_name: next_fauna
    # build
    image: node:16-alpine3.14
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/.next
      - /workspace/.vercel
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
