mutation CreateTodo($data: TodoInput!) {
  createTodo(data: $data) {
    _id
    completed
    task
    user {
      email
    }
  }
}
mutation CreateUser($data: UserInput!) {
  createUser(data: $data) {
    email
  }
}

mutation DeleteTodo($id: ID!) {
  deleteTodo(id: $id) {
    _id
    task
    completed
  }
}

mutation UpdateTodo(
  $id: ID!
  $data: PartialUpdateTodoInput!
) {
  partialUpdateTodo(id: $id, data: $data) {
    _id
    task
    completed
  }
}
