query User($email: String!) {
  user(email: $email) {
    _id
    email
    todos {
      data {
        _id
        completed
        task
      }
    }
  }
}

query FindTodoById($id: ID!) {
  findTodoByID(id: $id) {
    _id
    completed
    task
  }
}
